// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createStudyStmt, err = db.PrepareContext(ctx, createStudy); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStudy: %w", err)
	}
	if q.getStudiesStmt, err = db.PrepareContext(ctx, getStudies); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudies: %w", err)
	}
	if q.getStudyByIDStmt, err = db.PrepareContext(ctx, getStudyByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudyByID: %w", err)
	}
	if q.getStudyByPatientStmt, err = db.PrepareContext(ctx, getStudyByPatient); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudyByPatient: %w", err)
	}
	if q.softDeleteAllStudiesStmt, err = db.PrepareContext(ctx, softDeleteAllStudies); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteAllStudies: %w", err)
	}
	if q.softDeleteStudyStmt, err = db.PrepareContext(ctx, softDeleteStudy); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteStudy: %w", err)
	}
	if q.updateStudyDicomLinkStmt, err = db.PrepareContext(ctx, updateStudyDicomLink); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStudyDicomLink: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createStudyStmt != nil {
		if cerr := q.createStudyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStudyStmt: %w", cerr)
		}
	}
	if q.getStudiesStmt != nil {
		if cerr := q.getStudiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesStmt: %w", cerr)
		}
	}
	if q.getStudyByIDStmt != nil {
		if cerr := q.getStudyByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudyByIDStmt: %w", cerr)
		}
	}
	if q.getStudyByPatientStmt != nil {
		if cerr := q.getStudyByPatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudyByPatientStmt: %w", cerr)
		}
	}
	if q.softDeleteAllStudiesStmt != nil {
		if cerr := q.softDeleteAllStudiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteAllStudiesStmt: %w", cerr)
		}
	}
	if q.softDeleteStudyStmt != nil {
		if cerr := q.softDeleteStudyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteStudyStmt: %w", cerr)
		}
	}
	if q.updateStudyDicomLinkStmt != nil {
		if cerr := q.updateStudyDicomLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStudyDicomLinkStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	createStudyStmt          *sql.Stmt
	getStudiesStmt           *sql.Stmt
	getStudyByIDStmt         *sql.Stmt
	getStudyByPatientStmt    *sql.Stmt
	softDeleteAllStudiesStmt *sql.Stmt
	softDeleteStudyStmt      *sql.Stmt
	updateStudyDicomLinkStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		createStudyStmt:          q.createStudyStmt,
		getStudiesStmt:           q.getStudiesStmt,
		getStudyByIDStmt:         q.getStudyByIDStmt,
		getStudyByPatientStmt:    q.getStudyByPatientStmt,
		softDeleteAllStudiesStmt: q.softDeleteAllStudiesStmt,
		softDeleteStudyStmt:      q.softDeleteStudyStmt,
		updateStudyDicomLinkStmt: q.updateStudyDicomLinkStmt,
	}
}
