// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateStudy(ctx context.Context, arg CreateStudyParams) (Study, error)
	GetStudies(ctx context.Context, arg GetStudiesParams) ([]Study, error)
	GetStudyByID(ctx context.Context, id uuid.UUID) (Study, error)
	GetStudyByPatient(ctx context.Context, patient string) (Study, error)
	SoftDeleteAllStudies(ctx context.Context) error
	SoftDeleteStudy(ctx context.Context, id uuid.UUID) error
	UpdateStudyDicomLink(ctx context.Context, arg UpdateStudyDicomLinkParams) (Study, error)
}

var _ Querier = (*Queries)(nil)
