package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratedGitignoreSectionCanBeRemovedWithoutTouchingCustomContent(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".gitignore")
	content := "custom.txt\n# rest_generator:begin\nbin/\n# rest_generator:end\nkeep.txt\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedSection(path, "# rest_generator:begin", "# rest_generator:end"); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), "rest_generator") || !strings.Contains(string(got), "custom.txt") || !strings.Contains(string(got), "keep.txt") {
		t.Fatalf("unexpected .gitignore after generated section removal:\n%s", got)
	}
}

func TestRemoveGeneratedEnvPreservesUserFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".env")
	if err := os.WriteFile(path, []byte("CUSTOM=value\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedEnv(path); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("user-managed .env must be preserved: %v", err)
	}
	if err := os.WriteFile(path, []byte("# Code generated by rest_generator.\nVALUE=test\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedEnv(path); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("generator-managed .env must be removed, got %v", err)
	}
}

func TestBuildInitialMigration(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "users.sql"), []byte("CREATE TABLE users (id UUID PRIMARY KEY);\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	tables, err := readSchemaTables([]string{dir})
	if err != nil {
		t.Fatal(err)
	}
	migration, err := buildInitialMigration([]string{dir}, tables)
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{"-- Code generated by rest_generator.", "-- +goose Up", "CREATE TABLE users", "-- +goose Down", "DROP TABLE IF EXISTS users CASCADE;"} {
		if !strings.Contains(migration, expected) {
			t.Fatalf("migration does not contain %q:\n%s", expected, migration)
		}
	}
}

func TestReadSchemaTablesIgnoresCommentedExamples(t *testing.T) {
	dir := t.TempDir()
	schema := "-- Example:\n-- CREATE TABLE items (id UUID PRIMARY KEY);\n\nCREATE TABLE books (id UUID PRIMARY KEY);\n"
	if err := os.WriteFile(filepath.Join(dir, "schema.sql"), []byte(schema), 0o644); err != nil {
		t.Fatal(err)
	}
	tables, err := readSchemaTables([]string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if len(tables) != 1 || tables[0].Name != "books" {
		t.Fatalf("commented schema produced tables: %+v", tables)
	}
}

func TestRemoveGeneratedMigrationPreservesUserMigration(t *testing.T) {
	path := filepath.Join(t.TempDir(), "00001_rest_generator_init.sql")
	if err := os.WriteFile(path, []byte("-- handwritten\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedMigration(path); err == nil {
		t.Fatal("expected refusal to remove a user-managed migration")
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("user-managed migration was removed: %v", err)
	}
}
