package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratedGitignoreSectionCanBeRemovedWithoutTouchingCustomContent(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".gitignore")
	content := "custom.txt\n# rest:begin\nbin/\n# rest:end\nkeep.txt\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedSection(path, "# rest:begin", "# rest:end"); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), "# rest:") || !strings.Contains(string(got), "custom.txt") || !strings.Contains(string(got), "keep.txt") {
		t.Fatalf("unexpected .gitignore after generated section removal:\n%s", got)
	}
}

func TestRemoveGeneratedEnvPreservesUserFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".env")
	if err := os.WriteFile(path, []byte("CUSTOM=value\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedEnv(path); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("user-managed .env must be preserved: %v", err)
	}
	if err := os.WriteFile(path, []byte("# Code generated by rest.\nVALUE=test\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedEnv(path); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("generator-managed .env must be removed, got %v", err)
	}
}

func TestBuildInitialMigration(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "users.sql"), []byte("CREATE TABLE users (id UUID PRIMARY KEY);\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	tables, err := readSchemaTables([]string{dir})
	if err != nil {
		t.Fatal(err)
	}
	migration, err := buildInitialMigration([]string{dir}, tables)
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{"-- Code generated by rest.", "-- +goose Up", "CREATE TABLE users", "-- +goose Down", "DROP TABLE IF EXISTS users CASCADE;"} {
		if !strings.Contains(migration, expected) {
			t.Fatalf("migration does not contain %q:\n%s", expected, migration)
		}
	}
}

func TestReadSchemaTablesIgnoresCommentedExamples(t *testing.T) {
	dir := t.TempDir()
	schema := "-- Example:\n-- CREATE TABLE items (id UUID PRIMARY KEY);\n\nCREATE TABLE books (id UUID PRIMARY KEY);\n"
	if err := os.WriteFile(filepath.Join(dir, "schema.sql"), []byte(schema), 0o644); err != nil {
		t.Fatal(err)
	}
	tables, err := readSchemaTables([]string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if len(tables) != 1 || tables[0].Name != "books" {
		t.Fatalf("commented schema produced tables: %+v", tables)
	}
}

func TestReadSchemaTablesSupportsCommonPostgresTypesAndSchemas(t *testing.T) {
	dir := t.TempDir()
	schema := `
CREATE SCHEMA clinical;

CREATE TABLE clinical.studies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title CHARACTER VARYING(255) NOT NULL,
    metadata JSONB,
    tags TEXT[] NOT NULL,
    scores BIGINT[] NOT NULL,
    rating NUMERIC(10, 2),
    precision_score DOUBLE PRECISION,
    ratio REAL,
    attempts BIGINT,
    active BOOLEAN NOT NULL DEFAULT false,
    starts_at TIMESTAMP WITH TIME ZONE,
    birth_date DATE,
    CONSTRAINT studies_title_unique UNIQUE (title),
    CHECK (rating >= 0)
);
`
	if err := os.WriteFile(filepath.Join(dir, "schema.sql"), []byte(schema), 0o644); err != nil {
		t.Fatal(err)
	}
	tables, err := readSchemaTables([]string{dir})
	if err != nil {
		t.Fatal(err)
	}
	if len(tables) != 1 {
		t.Fatalf("expected one table, got %+v", tables)
	}
	table := tables[0]
	if table.Name != "studies" || table.SQLName != "clinical.studies" || table.GoName != "Study" {
		t.Fatalf("unexpected schema-qualified table parsing: %+v", table)
	}
	columns := map[string]column{}
	for _, col := range table.Columns {
		columns[col.Name] = col
	}
	checks := map[string]string{
		"id":              "uuid.UUID",
		"title":           "string",
		"metadata":        "string",
		"tags":            "[]string",
		"scores":          "[]int64",
		"rating":          "float64",
		"precision_score": "float64",
		"ratio":           "float32",
		"attempts":        "int64",
		"active":          "bool",
		"starts_at":       "time.Time",
		"birth_date":      "time.Time",
	}
	for name, goType := range checks {
		if columns[name].GoType != goType {
			t.Fatalf("column %s GoType = %q, want %q; columns=%+v", name, columns[name].GoType, goType, table.Columns)
		}
	}
	if !columns["starts_at"].NeedsTime || !columns["id"].NeedsUUID {
		t.Fatalf("expected time/uuid imports to be detected: %+v", table.Columns)
	}
	migration, err := buildInitialMigration([]string{dir}, tables)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(migration, "DROP TABLE IF EXISTS clinical.studies CASCADE;") {
		t.Fatalf("schema-qualified migration down is missing:\n%s", migration)
	}
}

func TestRemoveGeneratedMigrationPreservesUserMigration(t *testing.T) {
	path := filepath.Join(t.TempDir(), "00001_rest_init.sql")
	if err := os.WriteFile(path, []byte("-- handwritten\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeGeneratedMigration(path); err == nil {
		t.Fatal("expected refusal to remove a user-managed migration")
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("user-managed migration was removed: %v", err)
	}
}

func TestDockerComposeTemplateIncludesAppAndPostgres(t *testing.T) {
	data := renderData{
		Features: FeatureOptions{
			Build: BuildFeatures{
				DBName: "myapp_db", DBUser: "app_user", DBPassword: "app_password", DBOptions: "sslmode=disable",
			},
			Docker: DockerFeatures{
				Output: "Dockerfile", Port: 8080,
			},
		},
	}
	rendered, err := renderTemplateForTest(t, "docker-compose.yml", dockerComposeTemplate, data)
	if err != nil {
		t.Fatal(err)
	}
	text := string(rendered)
	for _, expected := range []string{
		"services:",
		"app:",
		"postgres:",
		`DB_DSN: "postgres://app_user:app_password@postgres:5432/myapp_db?sslmode=disable"`,
		"pg_isready -U app_user -d myapp_db",
	} {
		if !strings.Contains(text, expected) {
			t.Fatalf("docker compose template missing %q:\n%s", expected, text)
		}
	}
}
