package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func readSQLCConfig(path string) (sqlcConfig, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return sqlcConfig{}, err
	}
	var document struct {
		SQL []struct {
			Queries pathList `yaml:"queries"`
			Schema  pathList `yaml:"schema"`
			Gen     struct {
				Go struct {
					Package string `yaml:"package"`
					Out     string `yaml:"out"`
				} `yaml:"go"`
			} `yaml:"gen"`
		} `yaml:"sql"`
	}
	if err := yaml.Unmarshal(b, &document); err != nil {
		return sqlcConfig{}, fmt.Errorf("parse sqlc config: %w", err)
	}
	if len(document.SQL) == 0 {
		return sqlcConfig{}, fmt.Errorf("sqlc config must define at least one sql entry")
	}
	entry := document.SQL[0]
	cfg := sqlcConfig{QueriesDirs: []string(entry.Queries), SchemaDirs: []string(entry.Schema), DBPackage: entry.Gen.Go.Package, DBOut: entry.Gen.Go.Out}
	if cfg.DBPackage == "" {
		cfg.DBPackage = "db"
	}
	if len(cfg.SchemaDirs) == 0 || len(cfg.QueriesDirs) == 0 || cfg.DBOut == "" {
		return sqlcConfig{}, fmt.Errorf("sqlc config must define queries, schema and gen.go.out")
	}
	baseDir, err := filepath.Abs(filepath.Dir(path))
	if err != nil {
		return sqlcConfig{}, err
	}
	for i := range cfg.QueriesDirs {
		cfg.QueriesDirs[i] = resolveSQLCPath(baseDir, cfg.QueriesDirs[i])
	}
	for i := range cfg.SchemaDirs {
		cfg.SchemaDirs[i] = resolveSQLCPath(baseDir, cfg.SchemaDirs[i])
	}
	cfg.DBOut = resolveSQLCPath(baseDir, cfg.DBOut)
	return cfg, nil
}

type pathList []string

func (p *pathList) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind == yaml.ScalarNode {
		var value string
		if err := node.Decode(&value); err != nil {
			return err
		}
		*p = pathList{value}
		return nil
	}
	var values []string
	if err := node.Decode(&values); err != nil {
		return err
	}
	*p = values
	return nil
}

func resolveSQLCPath(baseDir, path string) string {
	if filepath.IsAbs(path) {
		return filepath.Clean(path)
	}
	return filepath.Clean(filepath.Join(baseDir, path))
}

func readModule(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(b), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", fmt.Errorf("module declaration not found in %s", path)
}

func readSchemaTables(schemaDirs []string) ([]table, error) {
	var files []string
	for _, schemaDir := range schemaDirs {
		matches, err := filepath.Glob(filepath.Join(schemaDir, "*.sql"))
		if err != nil {
			return nil, err
		}
		files = append(files, matches...)
	}
	sort.Strings(files)

	var sql strings.Builder
	for _, file := range files {
		b, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}
		sql.WriteByte('\n')
		sql.WriteString(stripSQLLineComments(string(b)))
	}

	re := regexp.MustCompile(`(?is)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?("?[\w]+"?)\s*\((.*?)\);`)
	matches := re.FindAllStringSubmatch(sql.String(), -1)
	tables := make([]table, 0, len(matches))
	for _, match := range matches {
		name := cleanIdent(match[1])
		tbl := table{
			Name:      name,
			Singular:  singular(name),
			Plural:    name,
			RouteBase: "/" + name,
		}
		tbl.GoName = exported(tbl.Singular)
		tbl.GoPlural = exported(tbl.Plural)
		tbl.Columns = parseColumns(match[2])
		for _, col := range tbl.Columns {
			if !col.ReadOnly {
				tbl.CreateCols = append(tbl.CreateCols, col)
			}
		}
		tables = append(tables, tbl)
	}
	return tables, nil
}

func stripSQLLineComments(source string) string {
	var cleaned strings.Builder
	for _, line := range strings.Split(source, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "--") {
			cleaned.WriteByte('\n')
			continue
		}
		cleaned.WriteString(line)
		cleaned.WriteByte('\n')
	}
	return cleaned.String()
}

func buildInitialMigration(schemaDirs []string, tables []table) (string, error) {
	var files []string
	for _, schemaDir := range schemaDirs {
		matches, err := filepath.Glob(filepath.Join(schemaDir, "*.sql"))
		if err != nil {
			return "", err
		}
		files = append(files, matches...)
	}
	sort.Strings(files)
	var migration strings.Builder
	migration.WriteString("-- Code generated by rest_generator. DO NOT EDIT.\n")
	migration.WriteString("-- +goose Up\n-- +goose StatementBegin\n")
	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			return "", err
		}
		migration.Write(content)
		if len(content) > 0 && content[len(content)-1] != '\n' {
			migration.WriteByte('\n')
		}
	}
	migration.WriteString("-- +goose StatementEnd\n\n-- +goose Down\n-- +goose StatementBegin\n")
	for i := len(tables) - 1; i >= 0; i-- {
		fmt.Fprintf(&migration, "DROP TABLE IF EXISTS %s CASCADE;\n", tables[i].Name)
	}
	migration.WriteString("-- +goose StatementEnd\n")
	return migration.String(), nil
}

func parseColumns(body string) []column {
	var cols []column
	for _, raw := range strings.Split(body, "\n") {
		line := strings.TrimSpace(strings.TrimSuffix(raw, ","))
		if line == "" || strings.HasPrefix(line, "--") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		name := cleanIdent(fields[0])
		upperName := strings.ToUpper(name)
		if upperName == "PRIMARY" || upperName == "CONSTRAINT" || upperName == "FOREIGN" || upperName == "UNIQUE" || upperName == "CHECK" {
			continue
		}
		sqlType := strings.ToUpper(strings.Trim(fields[1], ","))
		nullable := !strings.Contains(strings.ToUpper(line), "NOT NULL") && !strings.Contains(strings.ToUpper(line), "PRIMARY KEY")
		col := column{
			Name:     name,
			GoName:   exported(name),
			JSONName: name,
			Nullable: nullable,
			ReadOnly: isReadOnlyColumn(name) || strings.Contains(strings.ToUpper(line), "DEFAULT"),
		}
		col.Required = !col.Nullable && !col.ReadOnly && !strings.Contains(sqlType, "BOOL")
		col.GoType, col.DBValue, col.NeedsSQL, col.NeedsTime, col.NeedsUUID, col.ValidCheck = mapSQLType(sqlType, col)
		cols = append(cols, col)
	}
	return cols
}

func mapSQLType(sqlType string, col column) (goType, dbValue string, needsSQL, needsTime, needsUUID bool, validCheck string) {
	switch {
	case strings.Contains(sqlType, "UUID"):
		goType, dbValue, needsUUID = "uuid.UUID", col.GoName, true
		validCheck = "item." + col.GoName + " != uuid.Nil"
	case strings.Contains(sqlType, "INT"):
		goType = "int32"
		validCheck = "item." + col.GoName + " != 0"
		if col.Nullable {
			dbValue, needsSQL = fmt.Sprintf("sql.NullInt32{Int32: item.%s, Valid: item.%s != 0}", col.GoName, col.GoName), true
		} else {
			dbValue = col.GoName
		}
	case strings.Contains(sqlType, "TIME") || strings.Contains(sqlType, "DATE"):
		goType, needsTime = "time.Time", true
		validCheck = "!item." + col.GoName + ".IsZero()"
		if col.Nullable {
			dbValue, needsSQL = fmt.Sprintf("sql.NullTime{Time: item.%s, Valid: !item.%s.IsZero()}", col.GoName, col.GoName), true
		} else {
			dbValue = col.GoName
		}
	case strings.Contains(sqlType, "BOOL"):
		goType, dbValue = "bool", col.GoName
		validCheck = "item." + col.GoName
	default:
		goType = "string"
		validCheck = "item." + col.GoName + ` != ""`
		if col.Nullable {
			dbValue, needsSQL = fmt.Sprintf("sql.NullString{String: item.%s, Valid: item.%s != \"\"}", col.GoName, col.GoName), true
		} else {
			dbValue = col.GoName
		}
	}
	if !col.Nullable {
		dbValue = "item." + col.GoName
	}
	return
}

func isReadOnlyColumn(name string) bool {
	switch name {
	case "id", "created_at", "updated_at", "deleted":
		return true
	default:
		return false
	}
}
